### ISSUE TITLE
Pylint does not show the issues

### ISSUE THREAD

**Issue by Erossek** [AtomLinter/linter-pylint#53] opened 2015-08-11 09:09 UTC
I have installed pylint.
For atom I have: linter and linter-pylint.
In console when I write "pylint" it works, but in Atom I do not see any issues.
"Settings" of linter-pylint I have left empty.
I am using Windows 8.1.

What do I need to do to see python issues?

**Comment by gfarrell** [comment] 2015-08-11 13:33
I'm having this problem on OSX (10.10.4) using Atom 1.0.5, and the latest versions of linter and linter-pylint. Am trying to uninstall and reinstall all linter packages now.

**Comment by SpainTrain** [comment] 2015-08-11 18:39
Seeing similar on Ubuntu 14.10 Atom 1.0.5

**Comment by StuntsPT** [comment] 2015-08-11 23:21
Confirming on ArchLinux with Atom 1.0.5, linter 1.3.4, linter-pylint 0.2.2.
I do not see any errors on developer console. Only this line:
`Linter-Pylint: package loaded, ready to get initialized by AtomLinter.`

**Comment by jemartti** [comment] 2015-08-11 23:31
I believe this is a duplicate of #52

**Comment by StuntsPT** [comment] 2015-08-11 23:37
Confirming the fix in #52 works.
Seems indeed like a duplicate. Thanks @jemartti for pointing us in the right direction.

**Comment by gfarrell** [comment] 2015-08-12 11:49
This worked for me, thanks. Hopefully they'll update everything accordingly

**Comment by SpainTrain** [comment] 2015-08-13 15:44
Here's a PR https://github.com/AtomLinter/linter-pylint/pull/55 that updates to the new API; it should clear up this issue.  I tried to keep feature and behavior parity while following the latest atom linter patterns and conventions.  **Would love for some folks to test it out and shake out any bugs.**  If you are unfamiliar with installing dev packages from PRs, there are instructions in the PR description.  Thanks!

**Comment by steelbrain** [comment] 2015-08-20 18:20
Fixed by https://github.com/AtomLinter/linter-pylint/pull/55

**Closed by steelbrain** 2015-08-20 18:20 UTC
