### ISSUE TITLE
Pylint not found in spite of being installed and in shell PATH

### ISSUE THREAD

**Issue by mik01aj** [AtomLinter/linter-pylint#30] opened 2015-04-14 19:08 UTC
I get a following error:

```
Failed to spawn command `pylint`. Make sure `pylint` is installed and on your PATH
```

I have `pylint` in `/usr/local/bin/pylint` and it works when called from both bash and zsh. When I check the `process.env.PATH` from the Atom console, it says `/usr/bin:/bin:/usr/sbin:/sbin`. I wonder whether this is a bug linter-pylint, in Atom or some issue related to OS X config.

**Comment by mik01aj** [comment] 2015-04-14 19:20
Hmm, I have no idea why the path in Node was wrong, but I figured out I can give the path to pylint in settings. That worked. Thanks for the nice package! :)

**Comment by pmlamotte** [comment] 2015-04-24 14:59
Pylint used to be working for me, but doesn't anymore oddly enough. Specifying it manually fixed it in my case as well. I'm on OS X Yosemite.

**Comment by abdonrd** [comment] 2015-06-26 15:20
I have the same problem.
Fixed writing "/usr/local/bin/pylint" in the "Settings > Executable".

**Comment by MatthewHerbst** [comment] 2015-07-01 00:57
On OSX, I fixed this by doing:

```
sudo easy_install pip
pip install pylint
```

I would have thought the `linter-pylint` package would have covered that.

**Comment by JonnyCBB** [comment] 2015-07-08 10:39
I'm using Windows 8.1 and have Pylint install and in my path. If I open Atom from the terminal then everything is fine. However if I open atom from the Desktop Icon then Atom doesn't find Pylint :(

**Comment by SpainTrain** [comment] 2015-08-26 21:57
It appears that everyone on this thread has found a reasonable workaround.  Closing, but open a new issue if you are having similar problems!

**Closed by SpainTrain** 2015-08-26 21:57 UTC

**Comment by MatthewHerbst** [comment] 2015-08-26 22:00
@JonnyCBB that is a known issue with Atom - there is no ETA on the fix to my knowledge.

**Comment by SpainTrain** [comment] 2015-08-26 22:16
@MatthewHerbst do you have an upstream issue # handy (for folks that want to track it)?  I could only find https://github.com/atom/atom/issues/4126 which is marked as mac-specific. thx!

**Comment by MatthewHerbst** [comment] 2015-08-26 22:35
@SpainTrain I should have added the Mac clarification - it's unclear to me if the issue is present on Windows or Linux environments. The ticket you found is the one I am thinking of, in addition to [atom/atom#6956](https://github.com/atom/atom/issues/6956).

**Comment by mik01aj** [comment] 2015-08-27 07:40
Thanks @MatthewHerbst. In particular, the workaround [posted there by @mathiasringhof](https://github.com/atom/atom/issues/6956#issuecomment-126897491) using `launchctl` seems to be the best one can get now.

**Comment by JonnyCBB** [comment] 2015-08-27 11:41
Thanks @MatthewHerbst for letting me know.

**Comment by HologramOfMe** [comment] 2016-03-10 02:45
I'd like to make @abdonrd work around a little clearer because it's simple but for noobs no easy to understand how to arrive at solution. This will fix the error in Atom at least

First open a terminal (Linux, Mac, Unixy systems). If pylint is installed then the following will tell you where it is. Use the output of this command to fix the problem.

`which pylint`

Copy the output, which for me was "/usr/bin/pylint".

Then, in Atom, open Preferences (Settings), go to the Packages Tab on the left and search for the linter-pylint package by typing "pylint" into the search field.

Click on the package or the small settings button for that package and scroll to the settings section for the linter-pylint package. The first setting is titled Executable. That's the one you want.

Paste the output of the previous command you ran in the terminal into that field. It should now work just fine and dandy.

**Comment by erikdstock** [comment] 2016-03-22 15:58
This was an easy/obvious fix, but strange because it started out of nowhere after pylint was working in atom for me last week. I don't work much in python, either, so no big changes recently.

**Comment by Bosek** [comment] 2016-04-04 16:43
+1 
I have the same problem. JS linters work. Pylint doesn't. I can execute pylint from command line and location is in PATH.
Windows 8.1 64bit

**Comment by Arcanemagus** [comment] 2016-04-04 18:11
@Bosek if you manually specify the path to `pylint` (`where.exe pylint`) does it work?

**Comment by Bosek** [comment] 2016-04-04 18:23
```
C:\Python\Scripts\pylint.bat
C:\Python\Scripts\pylint.exe
```

I've also tried to specify executable path. No success.

**Comment by Arcanemagus** [comment] 2016-04-04 20:25
So if you enter `C:\Python\Scripts\pylint.exe` into the "Executable" setting you _still_ don't get any output?

**Comment by Bosek** [comment] 2016-04-04 20:54
`Uncaught BufferedProcessError: Failed to spawn command 'C:\Python\Scripts\pylint.exe'. Make sure 'C:\Python\Scripts\pylint.exe' is installed and on your PATH`

When I paste the path('C:\Python\Scripts\pylint.exe') into the cmd, it work of course.

**Comment by mit4dev** [comment] 2017-05-30 17:07
Installing pylint with the following code

`sudo pip install pylint`

solved my problem on Ubuntu 16.04

**Comment by HappyDoggo** [comment] 2017-10-22 23:37
`pip install pylint`
solved it on Windows 10 for me.

**Comment by Zoorken** [comment] 2018-11-09 20:49
Had the same problem today as Bosek has earlier described. 
`pip install pylint`
Worked for me both on Windows 10 and Ubuntu for me in the terminal.

Did not work in Pycharm. Got same error as Bosek.

**My solution**
Using the path to the pylint executor in the virtual environment instead. This was unclear to me since the plugin suggested the wrong executor.
