### ISSUE TITLE
Pylint-1.6.4 deprecation warnings

### ISSUE THREAD

**Issue by ashl1** [AtomLinter/linter-pylint#185] opened 2016-09-21 20:19 UTC
Atom with pylint-1.6.4 show the errors:

```
Error: This option u'ignore-iface-methods' will be removed in Pylint 2.0
This option u'required-attributes' will be removed in Pylint 2.0
    at /home/ashl1/.atom/packages/linter-pylint/lib/main.js:130:19
```

**Comment by marmistrz** [comment] 2016-10-05 14:09
The real problem is that it prevents the linter from working at all.

**Comment by Arcanemagus** [comment] 2016-10-10 21:30
@marmistrz The _real_ problem is that `pylint` is _insane_ and outputs valid content on both `stdout` _and_ `stderr`, so we need to consume both streams and attempt to figure out what is "good" content on `stderr`, and what we don't know about.

As for this deprecation message, I'm not really sure what to do about it... it looks like `pylint@2` isn't out yet so it sounds like these errors need to be turned into messages on the file itself (using a line of 0).

**Comment by Beatris** [comment] 2017-03-27 08:20
+1
Even when I remove the options from my pylintrc file the errors are still showing up. It's very disturbing and the linter does not work at all.

**Comment by ddaanet** [comment] 2017-05-10 08:37
I can reproduce this with with linter-pylint 2.0.1 and pylint-1.6.4.

The ignore-iface-method warning is no longer emitted by pylint-1.7.1. Since the bug report did not provide enough information to reproduce easily, I did not test for the other warning, but I expect it no longer emitted either.

Looking at the linter-pylint 2.0.1 code, here what seems to happen:

 1. Errors are read from stderr
```javascript
        const filteredErrors = filterWhitelistedErrors(data.stderr);
        if (filteredErrors) {
          // pylint threw an error we aren't ignoring!
          throw new Error(filteredErrors);
        }
```
 2. Lint messages are read from stdout
```javascript
        let match = lineRegex.exec(data.stdout);
        while (match !== null) {
          // ...snip...
          match = lineRegex.exec(data.stdout);
        }
```
So it appears @Arcanemagus comment is outdated.

I think an easy fix to the general "unexpected errors cause linter-pylint to crash" would be output filtered errors as Line 0 errors instead of `throw`ing them.

**Comment by Arcanemagus** [comment] 2017-05-10 17:24
The entire reason they are _whitelisted_ errors is that there is no way to know whether this is another case of `pylint` being... "unique" and outputting regular messages to `stderr`, or if `pylint` is crashing.

I could see adding deprecation messages like reported here to the list of whitelisted errors that are handled nicely, but if it's not a known error it's just as likely to be something like #212 which points to a major problem in the system setup.

**Comment by ddaanet** [comment] 2017-05-11 08:00
Right now, pylint does not print regular messages to stderr, and the code does not even makes an attempt to support this situation.

#212 is not a major problem in the system setup, it's likely just Fedora being what it is design to be (broken most of the time).

Unexpected stderr output should definitely be displayed, for the user to fix when the time is right for them. But it should not prevent processing of normal pylint output.

**Comment by clallen** [comment] 2017-07-24 00:07
If anyone else having this issue is using vim & Syntastic, upgrading Syntastic fixed the problem for me.  
I have Syntastic installed in ~/.vim/bundle, cloned from their github repo (https://github.com/scrooloose/syntastic.git), and just did a "git pull" to update it.

**Comment by ddaanet** [comment] 2018-01-09 14:52
Closing this issue, because it is old and no longer relevant to current pylint (the ignore-iface-method warning is no longer emitted by pylint-1.7.1)

The underlying problem is discussed in #216.

**Closed by ddaanet** 2018-01-09 14:52 UTC
Labels: bug, help wanted
