### ISSUE TITLE
Conflict with project modules

### ISSUE THREAD

**Issue by albertomontesg** [AtomLinter/linter-pylint#108] opened 2016-01-05 09:17 UTC
When I use pylint in Atom appears the following error:
```
Error: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pylint/lint.py", line 47, in <module>
    from pylint import checkers
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pylint/checkers/__init__.py", line 47, in <module>
    from pylint.config import OptionsProviderMixIn
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pylint/config.py", line 30, in <module>
    import optparse
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/optparse.py", line 421, in <module>
    _builtin_cvt = { "int" : (_parse_int, _("integer")),
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/gettext.py", line 498, in gettext
    return dgettext(_current_domain, message)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/gettext.py", line 462, in dgettext
    codeset=_localecodesets.get(domain))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/gettext.py", line 397, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/gettext.py", line 369, in find
    for nelang in _expand_lang(lang):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/gettext.py", line 112, in _expand_lang
    loc = locale.normalize(loc)
AttributeError: 'module' object has no attribute 'normalize'
```

Actually in project there is a module called also `locale` which seems to try to find the `normalize` attribute which actually is not in my project. If I rename my module in my project to other name (e.g. `locale2.py`) I find that pylint works perfectly.

**Comment by Arcanemagus** [comment] 2016-01-05 17:15
Does pylint from a terminal display the same issue?

**Comment by albertomontesg** [comment] 2016-01-06 12:20
No it doesn't. It's only displayed running at Atom

**Comment by Arcanemagus** [comment] 2016-01-06 18:27
I think this might be related to or a duplicate of #67, @SpainTrain you might know better than I if this is the case...

**Comment by Arcanemagus** [comment] 2016-06-07 22:02
Closing as a duplicate of #104.

**Closed by Arcanemagus** 2016-06-07 22:02 UTC
Labels: duplicate
