### ISSUE TITLE
Relative imports show error

### ISSUE THREAD

**Issue by pratyushmittal** [AtomLinter/linter-pylint#58] opened 2015-08-20 19:49 UTC
Relative imports in the project show errors.

Replacing `args.push tmpFilename` with `args.push file` in line 79 solves the problem.

**Comment by SpainTrain** [comment] 2015-08-20 19:57
> Replacing args.push tmpFilename with args.push file in line 79 solves the problem.

But it breaks on-the-fly linting :wink: 

I'll see if there isn't another solution to have both work.

**Comment by pratyushmittal** [comment] 2015-08-21 07:07
Couple of workarounds might be:

1. Create temporary file in the same folder as the file.
2. Adding filepath in the PYTHONPATH.

**Comment by SpainTrain** [comment] 2015-08-26 21:52
> Adding filepath in the PYTHONPATH.

Good call, I did something similar.  Feel free to test #61 to ensure it fixes your issue (fixed my local bug repro)

**Comment by ssbarnea** [comment] 2015-10-07 15:59
Am I wrong or this is the cause why I do get false positives because I do something like "from tp import xxx" where `tp.py` file exists near the file importing this. Still, the linter does give an error because it does load the "tp" module from python PATH?! (instead of the one from the current directory)

**Comment by Arcanemagus** [comment] 2016-06-07 21:48
Marking this as a duplicate of #57 as the root cause (temporary file hackery) is the same, and more relevant information is included over there (especially a test case this PYTHONPATH hackery proposed here seems to not work well with).

**Closed by Arcanemagus** 2016-06-07 21:48 UTC

**Comment by tutuca** [comment] 2017-01-12 13:18
I have this annoying behavior:

     # tests.py
     from .connectors import DBConnector

![image](https://cloud.githubusercontent.com/assets/70032/21891210/3b3fb360-d8b0-11e6-9e8a-4df1e9716e25.png)

It's failing to import the sibling module.

**Comment by Horta** [comment] 2017-02-15 15:19
I have exactly the same problem as @tutuca
