### ISSUE TITLE
Add support for arbitrary pylint arguments

### ISSUE THREAD

**Issue by hanks42** [AtomLinter/linter-pylint#92] opened 2015-11-25 21:29 UTC
I'd like to send pylint arguments like disabling certain messages and changing the max line length. There should be a way to send arbitrary arguments into pylint when it runs. For example to send these arguments I had to edit the plugin source

--max-line-length=100 -d I0011,C0303

**Comment by SpainTrain** [comment] 2015-11-25 21:31
Thanks for the enhancement suggestion.

Does using an rcfile for this not fit your use case?

**Comment by hanks42** [comment] 2015-11-25 21:43
Ah yes it does actually thanks! I saw the rcfile option but wasn't familiar with it's purpose.

**Comment by SpainTrain** [comment] 2015-11-25 22:01
Great!  I will leave this open as "PR welcome" in case someone does end up with a use case for this.

**Comment by Arcanemagus** [comment] 2016-05-04 23:52
Marking this as a duplicate of #113 since it contains a bit more information.

**Closed by Arcanemagus** 2016-05-04 23:52 UTC
Labels: enhancement, help wanted
