### ISSUE TITLE
[Linter] Error running Pylint

### ISSUE THREAD

**Issue by abdulazizasiri** [AtomLinter/linter-pylint#230] opened 2017-10-06 04:46 UTC
Pylint does not work on Atom. 

I get this issue. See Console for more info. (Open View -> Developer -> Toggle Developer Tools)

**Comment by dmatija** [comment] 2017-10-29 19:34
Same here... I fresh install atom on new PC and got same issue.
If i type something i got that popup on every letter i press.

**Comment by aaroncoffey** [comment] 2017-12-14 19:16
I was getting the same error, looks like it's not compatible with python2.6.
```
/Users/<USERNAME>/.atom/packages/linter/lib/linter-registry.js:159 [Linter] Error running Pylint Error: Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 7, in <module>
    from pylint import run_pylint
  File "/Library/Python/2.6/site-packages/pylint/__init__.py", line 8, in <module>
    from .__pkginfo__ import version as __version__
  File "/Library/Python/2.6/site-packages/pylint/__pkginfo__.py", line 50, in <module>
    if (py_version.major, py_version.minor) == (2, 7):
AttributeError: 'tuple' object has no attribute 'major'
    at Object.<anonymous> (/Users/<USERNAME>/.atom/packages/linter-pylint/lib/main.js:161:17)
    at Generator.next (<anonymous>)
    at step (/Users/<USERNAME>/.atom/packages/linter-pylint/lib/main.js:7:273)
```

**Comment by ddaanet** [comment] 2018-01-09 13:09
@abdulazizasiri @dmatija You did not provide enough information. You should follow the instructions and open the Console to get the traceback, like @aaroncoffey did.

@aaroncoffey Yes, pylint does not support python 2.6. I have project still on python 2.6 and I have python2.7 virtualenv just for pylint and friends.

There's nothing we can act on in this issue. So I am closing it. Please open another issue with more information if you still have a problem.

By the way make sure it is not a duplicate of #236, which was recently fixed, but whose fix is not released yet.

**Closed** 2018-01-09 13:09 UTC
